### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by OGtronTTV** [TakiiOS/PalguardEGGS#2]
Since the patch today, Steam v0.1.50 when installing this egg on a fresh server, anyone who connects to it will crash the server.
Ive tried using it stand alone, and also with palguard. Both crash instantly with my self and others trying to connect.
Not sure what changed or why but maybe you can fix it? Do you have a discord, or a discord ID I could talk to you in @TakiiOS

**Comment by TakiiOS** [comment]
Hi provide me : \Pal\Saved\Crashes\*random numbers*\CrashContext.runtime-xml file + palguard version used + log from Pal\Binaries\Win64\logs folder , Thanks.

**Comment by WareZ57** [comment]
> Since the patch today, Steam v0.1.50 when installing this egg on a fresh server, anyone who connects to it will crash the server. Ive tried using it stand alone, and also with palguard. Both crash instantly with my self and others trying to connect. Not sure what changed or why but maybe you can fix it? Do you have a discord, or a discord ID I could talk to you in @TakiiOS

Update Palguard manually, default the install version of the egg is not updated
https://www.nexusmods.com/palworld/mods/451?tab=files

**Comment by OGtronTTV** [comment]
> Hi provide me : \Pal\Saved\Crashes*random numbers*\CrashContext.runtime-xml file + palguard version used + log from Pal\Binaries\Win64\logs folder , Thanks.

As the post below you worked. But could you update your egg so it works with no error? as another person said 

Warning: Missing opening '"' in string property value: x.x.x.x,RCONEnabled=
True,RCONPort=27016,Region="",bUseAuth=True,BanListURL="https://api.palworldgame
.com/api/banlist.txt",bShowPlayerList=False)

and you cant change the pal.ini to fix it, and add -RCONPort=00000 to the startup field?
I use a bot that shows online players but using your egg, the bot cant access Rcon of the server for some reason.

**Comment by WareZ57** [comment]
> Author

You need to add quote ( " " ) to fix that. 

![image](https://github.com/TakiiOS/PalguardEGGS/assets/7504466/75f78ee5-ad97-4af4-b8d6-628f2b98e9b4)

And my startup line :
 ./PalworldServerConfigParser; (while read cmd; do rcon -s -a "localhost:$RCON_PORT" -p "$ADMIN_PASSWORD" "$cmd";done) < /dev/stdin & proton run /home/container/Pal/Binaries/Win64/PalServer-Win64-Test.exe Pal EpicApp=PalServer -publiclobby -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -port={{SERVER_PORT}} -publicport={{SERVER_PORT}} -servername="{{SERVER_NAME}}" -players={{MAX_PLAYERS}} $(if [ -n "$SERVER_PASSWORD" ]; then echo "-serverpassword="${SERVER_PASSWORD}""; fi) -adminpassword="{{ADMIN_PASSWORD}}" -rcon

**Comment by OGtronTTV** [comment]
> > Author
> 
> You need to add quote ( " " ) to fix that.
> 
> ![image](https://private-user-images.githubusercontent.com/7504466/309447210-75f78ee5-ad97-4af4-b8d6-628f2b98e9b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MDc3NjAsIm5iZiI6MTcwOTQwNzQ2MCwicGF0aCI6Ii83NTA0NDY2LzMwOTQ0NzIxMC03NWY3OGVlNS1hZDk3LTRhZjQtYjhkNi02MjhmMmI5OGU5YjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDJUMTkyNDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGUzMmVjODE4M2U5YmE1NTY4MWE2ZmQ1ZTU2MDVjYzU3YjkyZTc4NjFkZmViMWRkZDYxZGY4OTE5NzE2MWJhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ggbkoPctgYE243aYYS23C06R-yd0RHXE-S1lUdsj3Is)
> 
> And my startup line : ./PalworldServerConfigParser; (while read cmd; do rcon -s -a "localhost:$RCON_PORT" -p "$ADMIN_PASSWORD" "$cmd";done) < /dev/stdin & proton run /home/container/Pal/Binaries/Win64/PalServer-Win64-Test.exe Pal EpicApp=PalServer -publiclobby -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -port={{SERVER_PORT}} -publicport={{SERVER_PORT}} -servername="{{SERVER_NAME}}" -players={{MAX_PLAYERS}} $(if [ -n "$SERVER_PASSWORD" ]; then echo "-serverpassword="${SERVER_PASSWORD}""; fi) -adminpassword="{{ADMIN_PASSWORD}}" -rcon

Seemed to work thanks!

Also does anyone know why a custom Discord Bot that can pull the Steam ID/Player IDs no longer works with the egg?
My bot still works with a different egg so im wonder what broke with the last up date for this egg. Wish Takii could update it ;)

**Comment by WareZ57** [comment]
> > > Author
> > 
> > 
> > You need to add quote ( " " ) to fix that.
> > ![image](https://private-user-images.githubusercontent.com/7504466/309447210-75f78ee5-ad97-4af4-b8d6-628f2b98e9b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MDc3NjAsIm5iZiI6MTcwOTQwNzQ2MCwicGF0aCI6Ii83NTA0NDY2LzMwOTQ0NzIxMC03NWY3OGVlNS1hZDk3LTRhZjQtYjhkNi02MjhmMmI5OGU5YjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDJUMTkyNDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGUzMmVjODE4M2U5YmE1NTY4MWE2ZmQ1ZTU2MDVjYzU3YjkyZTc4NjFkZmViMWRkZDYxZGY4OTE5NzE2MWJhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ggbkoPctgYE243aYYS23C06R-yd0RHXE-S1lUdsj3Is)
> > And my startup line : ./PalworldServerConfigParser; (while read cmd; do rcon -s -a "localhost:$RCON_PORT" -p "$ADMIN_PASSWORD" "$cmd";done) < /dev/stdin & proton run /home/container/Pal/Binaries/Win64/PalServer-Win64-Test.exe Pal EpicApp=PalServer -publiclobby -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -port={{SERVER_PORT}} -publicport={{SERVER_PORT}} -servername="{{SERVER_NAME}}" -players={{MAX_PLAYERS}} $(if [ -n "$SERVER_PASSWORD" ]; then echo "-serverpassword="${SERVER_PASSWORD}""; fi) -adminpassword="{{ADMIN_PASSWORD}}" -rcon
> 
> Seemed to work thanks!
> 
> Also does anyone know why a custom Discord Bot that can pull the Steam ID/Player IDs no longer works with the egg? My bot still works with a different egg so im wonder what broke with the last up date for this egg. Wish Takii could update it ;)

Since the last update, the RCON no longer works with the bots.

I haven't found a solution to this problem.


However, I want to inform you that the egg has memory leaks after 1 hour with 10 players, the server uses 64 GB of RAM. I strongly advise you to switch to Windows.

The creator of the egg and even the person who provided the code aren't responding, so I think you can drop it.

Here's my Discord: pandanounet

**Comment by OGtronTTV** [comment]
> Since the last update, the RCON no longer works with the bots.
> 
> I haven't found a solution to this problem.
> 
> However, I want to inform you that the egg has memory leaks after 1 hour with 10 players, the server uses 64 GB of RAM. I strongly advise you to switch to Windows.
> 
> The creator of the egg and even the person who provided the code aren't responding, so I think you can drop it.
> 
> Here's my Discord: pandanounet

Yea indeed. I got my discord bot working again so im happy =)

**Comment by TakiiOS** [comment]
Update at : 05.03.2024 AT 15H Thanks for response.
