### ISSUE TITLE
Default egg installation wrong Pal / Saved / Config / WindowsServer / PalWorldSettings.ini file

### ISSUE THREAD

**Issue by scaki1** [TakiiOS/PalguardEGGS#3]
Hello,

Just tested your egg. Great work ! 

I get following error on startup and i even tried to edit startup command to add changes but on every startup they get back to default.

Warning: Missing opening '"' in string property value: 145.239.233.128,RCONEnabl
ed=True,RCONPort=5005,Region="",bUseAuth=True,BanListURL="https://api.palworldga
me.com/api/banlist.txt")

Your default egg is 
PublicIP=145.239.233.128,RCONEnabled=True,

Where it should be 

PublicIP="145.239.233.128",RCONEnabled=True

**Comment by OGtronTTV** [comment]
> Hello,
> 
> Just tested your egg. Great work !
> 
> I get following error on startup and i even tried to edit startup command to add changes but on every startup they get back to default.
> 
> Warning: Missing opening '"' in string property value: 145.239.233.128,RCONEnabl ed=True,RCONPort=5005,Region="",bUseAuth=True,BanListURL="https://api.palworldga me.com/api/banlist.txt")
> 
> Your default egg is PublicIP=145.239.233.128,RCONEnabled=True,
> 
> Where it should be
> 
> PublicIP="145.239.233.128",RCONEnabled=True

How can you fix this? I tried fixing in the ini file but it keeps changing back to default. I changed the startup params and same thing.

**Comment by TakiiOS** [comment]
Update at : 05.03.2024 AT 15H Thanks for response.
